open-y-subprojects/openy_features

composer.json
It should be not in Open Y core, but here
https://github.com/ymcatwincities/openy/blob/9.x-2.x/composer.json#L121
=> feat(decouple): Return back node_session

openy_block/modules/openy_block_branch_amenities/openy_block_branch_amenities.info.yml
If openy_ckeditor is not enabled amenities block doesn't work properly.
=> Added openy_ckeditor as dependency to openy_block_branch_amenitites.

openy_block/modules/openy_block_branch_contacts_info/src/Plugin/Block/BranchContactsInfo.php
Adds early returns and check if field_branch_hours exist on the node.
=> Check if field_branch_hours exists.

openy_prgf/modules/openy_prgf_loc_finder/SMOKE_TESTS.md
Fixed-by: @podarok
Added-to: https://github.com/ymcatwincities/openy/wiki/Open-Y-Smoke-Tests-Index
=> docs(qa,smoke tests): Add Location Finder tests

openy_prgf/modules/openy_prgf_small_banner/SMOKE_TESTS.md
Fixed-by: @podarok
Extends: https://github.com/ymcatwincities/openy/wiki/Open-Y-Smoke-Tests-Index
=> docs(qa,smoke tests): Add Small Banner smoke tests

openy_prgf/modules/openy_prgf_simple_content/SMOKE_TESTS.md
Fixed-by: @podarok
Extends: https://github.com/ymcatwincities/openy/wiki/Open-Y-Smoke-Tests-Index
=> docs(qa,smoke tests): Add Simple Content tests

openy_prgf/modules/openy_prgf_banner/SMOKE_TESTS.md, openy_prgf/modules/openy_prgf_simple_content/SMOKE_TESTS.md
Fixed-by: @podarok
Extends: https://github.com/ymcatwincities/openy/wiki/Open-Y-Smoke-Tests-Index
=> docs(qa,smoke tests): Add Banner smoke tests

openy_prgf/modules/openy_prgf_grid_content/SMOKE_TESTS.md
Extends: https://github.com/ymcatwincities/openy/wiki/Open-Y-Smoke-Tests-Index#open-y-features
=> docs(qa,smoke tests): Add Paragraph Grid Content

openy_prgf/modules/openy_prgf_pgm_reg/openy_prgf_pgm_reg.info.yml
Addresses: https://openy.atlassian.net/browse/MAINTAIN-72 and https://github.com/ymcatwincities/openy/issues/2369
Explained-in: https://openy.atlassian.net/browse/MAINTAIN-72?focusedCommentId=12533
Unblocks: https://github.com/ymcatwincities/openy/pull/2559
Requested-by: @ddrozdik
=> feat!: Deprecate Daxko Program Registration Paragraph

openy_taxonomy/src/Plugin/views/filter/BetterTaxonomyIndexTid.php
Hi, @podarok 
We have a project with unpublished Amenities items. In this case they are shown in the amenities block for all users.
To fix that we've prepared this small patch.
=> Fix issues with unpublished amenities

openy_location/modules/openy_loc_branch/config/install/core.entity_form_display.node.branch.default.yml, openy_location/modules/openy_loc_branch/config/install/field.field.node.branch.field_location_directions.yml, openy_location/modules/openy_loc_branch/openy_loc_branch.install, openy_location/modules/openy_loc_camp/config/install/core.entity_form_display.node.camp.default.yml, openy_location/modules/openy_loc_camp/config/install/field.field.node.camp.field_location_directions.yml, openy_location/modules/openy_loc_camp/openy_loc_camp.install, openy_location/modules/openy_loc_facility/config/install/core.entity_form_display.node.facility.default.yml, openy_location/modules/openy_loc_facility/config/install/field.field.node.facility.field_location_directions.yml, openy_location/modules/openy_loc_facility/openy_loc_facility.install
resolves https://github.com/open-y-subprojects/openy_features/pull/23#issuecomment-1306136535.
It hasn't been long since the update so I thought just modifying the existing update hook should be ok, but if it would be better to create a new update I can do that @podarok. cc @andreyzb
=> fix: Update configs for branch, camp, facility

openy_editor/config/install/editor.editor.full_html.yml, openy_editor/config/install/filter.format.full_html.yml, openy_editor/openy_editor.info.yml, openy_editor/openy_editor.install
Related issues:
[DS-395](https://yusa.atlassian.net/browse/DS-395) 
[DS-396](https://yusa.atlassian.net/browse/DS-396)
Removed these buttons:
=> [DS-395] [DS-396] Remove Font Style and Font Size buttons from the editor panel

openy_user/openy_user.info.yml
Addresses: https://yusa.atlassian.net/browse/DS-583
=> Non existent permissions aren't allowed

composer.json, openy_user/openy_user.info.yml
Addresses: https://github.com/YCloudYUSA/yusaopeny/pull/8#issuecomment-1510938818
=> D10  - add dependency from google_analytics

openy_node/modules/openy_node_program/openy_node_program.info.yml
Fixes-step: https://github.com/YCloudYUSA/yusaopeny/pull/8#issuecomment-1520116434
=> fix: typo in version constraints

openy_egym_iwatch/openy_egym_iwatch.install, openy_media/modules/openy_media_document/src/Plugin/Field/FieldFormatter/FileIframeFormatter.php, openy_media/modules/openy_media_document/src/Plugin/Field/FieldFormatter/FileLinkFormatter.php, openy_media/modules/openy_media_image/src/Plugin/Field/FieldFormatter/ImageLinkFormatter.php
Same setup as https://github.com/open-y-subprojects/openy_custom/pull/24
=> fix: Additional D10 rector fixes

openy_node/modules/openy_node_event/openy_node_event.install
=> Update fails with invalid path

openy_editor/config/install/editor.editor.full_html.yml, openy_editor/config/install/filter.format.full_html.yml, openy_editor/openy_editor.install
Fixes this bug https://yusa.atlassian.net/browse/DS-749
=> fix: allow override view mode for media in ckeditor

openy_editor/config/install/editor.editor.full_html.yml, openy_editor/openy_editor.install
part of https://yusa.atlassian.net/browse/DS-946, also adds "Remove Format" button in what seems like a reasonable place because it's super useful. Also tries to resolve https://github.com/open-y-subprojects/openy_features/pull/63/files#r1300449668
=> fix: DS-946 Add dependency on ckeditor5_font

openy_node/openy_node.info.yml
unblocks https://github.com/YCloudYUSA/yusaopeny/pull/110
=> Ensure diff is installed on site install

openy_location/modules/openy_loc_facility/config/install/core.entity_form_display.node.facility.default.yml, openy_location/modules/openy_loc_facility/config/install/core.entity_view_display.node.facility.full.yml, openy_location/modules/openy_loc_facility/config/install/field.field.node.facility.field_branch_holiday_hours.yml, openy_location/modules/openy_loc_facility/config/install/field.field.node.facility.field_branch_hours.yml, openy_location/modules/openy_loc_facility/config/install/field.storage.node.field_branch_holiday_hours.yml, openy_location/modules/openy_loc_facility/config/install/field.storage.node.field_branch_hours.yml, openy_location/modules/openy_loc_facility/openy_loc_facility.install, openy_location/modules/openy_loc_facility/openy_loc_facility.module
https://yusa.atlassian.net/browse/DS-1119
=> feat: Include ability to add custom hours on Facility CT

openy_node/config/install/image.style.facebook.yml, openy_node/openy_node.install
[DS-1218](https://yusa.atlassian.net/browse/DS-1218)
=> [DS-1218] Remove convert to Webp format for Facebook image style.

openy_prgf/modules/openy_prgf_mbrshp_calc/config/install/core.entity_view_display.media.image.calc_preview.yml, openy_prgf/modules/openy_prgf_mbrshp_calc/config/install/core.entity_view_display.node.branch.calc_summary.yml, openy_prgf/modules/openy_prgf_mbrshp_calc/config/install/core.entity_view_display.node.membership.calc_summary.yml, openy_prgf/modules/openy_prgf_mbrshp_calc/openy_prgf_mbrshp_calc.install
Jira issue: [DS-1355](https://yusa.atlassian.net/browse/DS-1355)
Update config files for the Membership nodes
=> [DS-1355] Update configs after the Membership Calculator redesign

openy_editor/config/install/editor.editor.full_html.yml, openy_editor/openy_editor.install
Jira issue: [DS-1508](https://yusa.atlassian.net/browse/DS-1508)
=> [DS-1508] - Add a 'highlighted' element to the Ckeditor5 Style plugin

openy_menu/modules/openy_menu_utility/config/install/system.menu.utility.yml, openy_menu/modules/openy_menu_utility/openy_menu_utility.features.yml, openy_menu/modules/openy_menu_utility/openy_menu_utility.info.yml
[DS-1579](https://yusa.atlassian.net/browse/DS-1579)
=> DS-1579 feat: Add Utility Menu module.

openy_media/modules/openy_media_document/src/Plugin/Field/FieldFormatter/FileIframeFormatter.php
**Problem:** Certain file types cannot be displayed in <iframe> due to browser limitations and MIME type specifics.
**Issue:** https://jet-dev.atlassian.net/browse/ITCR-742
Description
1. log in as admin
2. Go to add content → create new post
3. In the Content Area field, find the insert media section. Add a csv file.
4. Enter any content creation, for example, create a new post
5. In the Content Area field, select the insert media section. In the insert media section field, select the Document section
6. The csv file starts downloading to the computer, although we did not select it or add it
=> [ITCR-742] Fix automatic file downloads

composer.json, openy_editor/config/install/editor.editor.full_html.yml
See this issue https://www.drupal.org/project/ckeditor5_font/issues/3456412 looks like this module mo more suported
TODO: use https://www.drupal.org/project/ckeditor5_plugin_pack
=> feat: remove deps ckeditor5_font

composer.json, openy_editor/config/install/editor.editor.full_html.yml, openy_editor/openy_editor.info.yml, openy_editor/openy_editor.install
backport code to 4.x from https://github.com/open-y-subprojects/openy_features/pull/102
=> Backport Migrate color font from 3.7.0
