- openy_media/modules/openy_media_video/openy_media_video.module
- openy_media/modules/openy_media_video/src/OpenyMediaVideoPreRender.php
Original Issue, this PR is going to fix: [MAINTAIN-151](https://openy.atlassian.net/browse/MAINTAIN-151)
Also this was discussed in this PR https://github.com/ymcatwincities/openy/pull/2526
The fix should add the border to all embedded video entities
> [MAINTAIN-151] changed a default value of the frameborder attribute to 1 for video_embed_iframe element

- openy_block/modules/openy_block_branch_contacts_info/src/Plugin/Block/BranchContactsInfo.php
- openy_location/modules/openy_loc_branch/config/install/core.entity_form_display.node.branch.default.yml
- openy_location/modules/openy_loc_branch/config/install/core.entity_view_display.node.branch.class_location.yml
- openy_location/modules/openy_loc_branch/config/install/core.entity_view_display.node.branch.default.yml
- openy_location/modules/openy_loc_branch/config/install/core.entity_view_display.node.branch.full.yml
- openy_location/modules/openy_loc_branch/config/install/core.entity_view_display.node.branch.sidebar_teaser.yml
- openy_location/modules/openy_loc_branch/config/install/core.entity_view_display.node.branch.teaser.yml
- openy_location/modules/openy_loc_branch/config/install/field.field.node.branch.field_branch_holiday_hours.yml
- openy_location/modules/openy_loc_branch/config/install/field.storage.node.field_branch_holiday_hours.yml
- openy_location/modules/openy_loc_branch/openy_loc_branch.install
To test use fresh OpenY setup with Demo content.
> Improvements for displaying Branch location holiday hours [YUOPENY-11]

- openy_block/modules/openy_block_branch_contacts_info/src/Plugin/Block/BranchContactsInfo.php
- openy_block/modules/openy_block_branch_contacts_info/templates/block-branch-contacts-info.html.twig
- openy_location/modules/openy_loc_branch/config/install/field.field.node.branch.field_location_directions.yml
- openy_location/modules/openy_loc_branch/openy_loc_branch.install
- openy_location/modules/openy_loc_camp/config/install/field.field.node.camp.field_location_directions.yml
- openy_location/modules/openy_loc_camp/openy_loc_camp.install
- openy_location/modules/openy_loc_facility/config/install/field.field.node.facility.field_location_directions.yml
- openy_location/modules/openy_loc_facility/openy_loc_facility.install
Steps to test:
Themes changes are required and will be provided through Merge requests on Drupal.org. 
Upgrade path possibly is required as well, at the moment solution works well for the clean OpenY installation.
> Ability to change the link text for "Directions" [YUOPENY-14]

- openy_block/modules/openy_code_block/config/install/filter.format.code.yml
- openy_block/modules/openy_code_block/openy_code_block.install
Resolves https://yusa.atlassian.net/browse/DS-331
The  `filter_htmlcorrector` in the Code Block is preventing direct pasting of embed codes from GXP (and possibly other places). As discussed in Slack this filter is unnecessary in the Code Block and can be removed.
To test:
- pull code and run `updb`
- visit `admin/config/content/formats/manage/code` and observe "Correct faulty and chopped off HTML" is unchecked.
> [DS-331] Remove filter_htmlcorrector from Code filter

- openy_location/modules/openy_loc_branch/openy_loc_branch.install
Previously if a site without openy_field_holiday_hours enabled ran the 8025 update, the configuration dependent on that module wouldn't be imported.
This doesn't do anything to address sites that have already run the 8025 update.
See also
- this Slack discussion: https://yusaslackinstance.slack.com/archives/C03E6SQQ0Q5/p1680083553972689
- https://github.com/YCloudYUSA/y_lb/issues/59 which has a similar open question about resolution imho.
Thanks!
> fix: enable openy_field_holiday_hours

- openy_node/modules/openy_node_activity/openy_node_activity.module
- openy_node/modules/openy_node_category/openy_node_category.module
- openy_node/modules/openy_node_class/openy_node_class.module
- openy_node/src/BatchNodeUpdate.php
**Ticket:** #38
Don't set batch updates with nothing to do. Don't error out if nothing can be loaded in the batch callback.
Thanks!
> #38: Add guards to node batch updates

- openy_prgf/modules/openy_prgf_event_listing/openy_prgf_event_listing.module
[DS-825](https://yusa.atlassian.net/browse/DS-825) [Accessibility] Event Post Listing (paragraphs) missing form label
Changes inaccessible placeholder title to a proper label for proper accessibility.
> DS-825 Move event listing placeholder text to label

- openy_prgf/modules/openy_prgf_faq/js/paragraph.js
- openy_prgf/modules/openy_prgf_faq/openy_prgf_faq.libraries.yml
As per https://www.drupal.org/node/3158256
FAQ accordions failed in D10 with `Uncaught TypeError: once is not a function` This resolved the issue.
> fix: Restore FAQ accordion functionality in D10

- openy_node/modules/openy_node_event/js/openy_node_event.js
- openy_node/modules/openy_node_event/openy_node_event.info.yml
- openy_node/modules/openy_node_event/openy_node_event.libraries.yml
- openy_node/modules/openy_node_event/openy_node_event.module
In order to improve accessibility of the addtocalendar functionality (that's mostly no longer maintained) I've moved that JS into https://github.com/froboy/openy_custom/tree/main/openy_system. Many modules have indirect dependencies there, but this formalizes that dependency.
> DS-858 Move addtocalendar js to openy_system

- openy_node/config/install/image.style.facebook.yml
- openy_node/openy_node.install
See https://developers.facebook.com/docs/sharing/webmasters/images/
> Use images that are at least 1200 x 630 pixels for the best display on high resolution devices. At the minimum, you should use images that are 600 x 315 pixels to display link page posts with larger images.
> fix: Update image style sizes as per 2023 recommendations

- composer.json
- openy_location/modules/openy_loc_branch/config/optional/metatag.metatag_defaults.node__branch.yml
- openy_location/modules/openy_loc_branch/openy_loc_branch.install
- openy_location/modules/openy_loc_camp/config/optional/metatag.metatag_defaults.node__camp.yml
- openy_location/modules/openy_loc_camp/openy_loc_camp.install
- openy_location/modules/openy_loc_facility/config/optional/metatag.metatag_defaults.node__facility.yml
- openy_location/modules/openy_loc_facility/openy_loc_facility.install
Adds metatags using Schema:LocalBusiness to Branch, Camp, and Facility content types.
To test:
- ensure database updates are run
- go to /admin/config/search/metatag and observe new entries for Branch, Camp, Facility
- Edit a Branch and populate the Branch Hours, Save
- Put the page url into https://search.google.com/test/rich-results and observe the Rich Results return with no errors (warnings may be returned) including opening hours.
- Do the same with Camp/Facility (no hours will be displayed since these content types don't have them
- Switch a Branch to Layout Builder, retest and the metadata should not change.
> DS-675 feat: DS-675 Add schema for branch, camp, facility

- composer.json
- openy_node/config/install/diff.settings.yml
- openy_node/openy_node.install
Add [diff module](https://www.drupal.org/project/diff) for better revision comparison. It’s got 90k installs and almost zero config. Seems like a great addition for the editor experience.
To test:
- Install or update
- Edit and save a node
- Visit **Revisions** and observe that you can now compare versions.
> DS-826 feat: Add diff module for rich revisions

- openy_editor/config/install/editor.editor.full_html.yml
- openy_editor/openy_editor.install
[DS-1256](https://yusa.atlassian.net/browse/DS-1256)
How to check:
> [DS-1256] Add WS colors to Ckeditor5's font color and background color plugins.

- openy_node/modules/openy_node_event/openy_node_event.module
**Steps to reproduce:**
1. Create an event with an empty description
2. Go to the review page with the error display enabled
> YGBWSLA-679: Fix deprication notice in strip_tags() function

- composer.json
- openy_media/modules/openy_media_local_video/config/install/field.field.media.video_local.field_media_local_video.yml
- openy_media/modules/openy_media_local_video/openy_media_local_video.install
- Visit /admin/content/browser
- “Add media”
- Check that “Video” accepts a youtube, vimeo, or youtube playlist
- Ensure you can add the video and then edit the metadata
- Check that “Local Video” accepts formats
- Ensure you can add the video and then edit the metadata
Adds contrib issue: https://www.drupal.org/node/3444172
> DS-1342 fix: Enable adding local video and remote video via media directories

- openy_editor/config/install/editor.editor.full_html.yml
- openy_editor/openy_editor.info.yml
- openy_editor/openy_editor.install
Original Issue, this PR is going to fix: [DS-1310](https://yusa.atlassian.net/browse/DS-1310)
> [DS-1310] Add the "CKEditor 5 Paste Filter" to the Full HTML editor configuration and enable it

- openy_media/modules/openy_media_image/config/install/core.entity_view_display.media.image.embedded_full.yml
- openy_media/modules/openy_media_image/config/install/core.entity_view_display.media.image.embedded_half.yml
- openy_media/modules/openy_media_image/openy_media_image.install
the images added through simple text/table are looking fine on android devices but they are not scalling well on the ios devices https://carnation-ws.y.org/events/test-event , this fix is working as expected in couple of our sites . link to issue https://yusa.atlassian.net/browse/DS-1549
> ds-1549:fix for responsive image issue on ios device.

- composer.json
- openy_editor/config/install/editor.editor.full_html.yml
- openy_editor/openy_editor.install
Jira issue: [DS-1605](https://yusa.atlassian.net/browse/DS-1605)
**Depends on** https://github.com/YCloudYUSA/y_lb/pull/247/
> [DS-1605] - Add styles for table

- openy_node/modules/openy_node_news/config/optional/core.entity_form_display.node.news.default.yml
- openy_node/modules/openy_node_news/openy_node_news.install
**Steps to reproduce:**
1. Login as an admin.
2. Navigate to Content → Add content → News Post.
3. In the Image field, upload a media item.
4. Notice that the image is not rendered correctly during content creation.
✅ **Solution:**
The form display setting for the Image field was updated to use Render entity with the Half without Blazy view mode.
> Fix image field Manage form display for News Post content type

- openy_editor/openy_editor.info.yml
fix for https://github.com/open-y-subprojects/openy_features/pull/98
> fix: remove   - drupal:ckeditor5_font from openy_editor

- openy_editor/openy_editor.info.yml
https://www.drupal.org/project/colorbutton and ckeditor_bootstrap_buttons,  ckeditor_font did not have drupal 11 version at this moment and we remove it from composer dependencies
> Update openy_editor.info.yml remove colorbutton dependency
